config/routes.rb
Rails.application.routes.draw do
  resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to @book, notice: 'Book was succcessfully created.'
    else
      render 'new'
  end
end

  def new
    @book = Book.new
   end

  def edit
  end

  def show
  end
  
  private
  def book_params
    params.require(:book).permit(:title, :description)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<div class = "container">
    
  <div class = "row">
     <div class = "col-sm-12 col-mg-12 col-lg-12 px-sm-0">
       <%= form_with model: book do |form| %>
       
       <% if book.errors.any? %>
       <%= book.errors.count %>prohibited this book from being saved
         <ul>
             <% book.errors.full_messages.each do |massage| %>
             <lil><%= massage %></lil>
             <% end %>
         </ul>
         <% end %>
    </div>
  </div>
    
  <div class = "row">
     <div class = "col-sm-12 col-mg-12 col-lg-12 px-sm-0">
       
         <div class = "row">
             <div class = "field">
                 <div class = "col-sm-6 col-mg-4 col-lg-2 px-sm-0">
                     <%= form.label :title %> 
                 </div>
                 <div class = "col-sm-4 col-mg-5 col-lg-6 px-sm-0">
                     <%= form.text_field :title %>
                  </div> 
             </div>
         </div>
         
          <div class = "row">
             <div class = "field">
                 <div class = "col-sm-6 col-mg-4 col-lg-2 px-sm-0">
                    <%= form.label :description %>
                 </div>
                 <div class = "col-sm-4 col-mg-5 col-lg-6 px-sm-0">
                    <%= form.text_field :description %>
                  </div> 
             </div>
         </div>
     </div>
  </div>
   <div class = "row mt-3">
     <div class = "col-sm-12 col-mg-12 col-lg-12 px-sm-0">
       <%= form.submit %>
    </div>
  </div>
  
  
  <% end %>
</div>

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<%= render 'form', book: @book %>
<%= link_to 'Show', @book %> | <%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<div class = "container">
  
  <p id = "notice"><%= notice%></p>
  <div class = "row m-4"><h1>Books</h1></div>

  <div class = "row">
    <div class = "col-sm-12 col-mg-12 col-lg-12 px-sm-0">
      <table>
        <thead>
          <tr>
            <th>Title</th>
            <th>Description</th>
            <th colspan = "3"></th>
          </tr>
        </thead>
        
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td><%= book.title %></td>
            <td><%= book.descripton %></td>
            <td><%= link_to "Show", book_path(book) %></td>
            <td><%= link_to "Edit", edit_book_path(book) %></td>
            <td><%= link_to "Destroy", book_path, method: :delete, "data-confirm" => "本当に削除しますか？"  %></td>
          </tr>
          <% end %>
        </tbody>
        
      </table>
    </div>
  </div>
  <div class = "row">
    <% link_to 'New Book',new_book_path %>
  </div>
 
</div>

app/views/books/new.html.erb
<div class = "container">
  <div class = "row">
     <div class = "col-sm-12 col-mg-12 col-lg-12 px-sm-0">
       <h1>New Book</h1>
         <%= render 'form', book: @book %>
         <%= link_to 'Back', books_path %>
    </div>
    
  </div>
</div>

app/views/books/show.html.erb
<h1>Books#show</h1>
<p>Find me in app/views/books/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<
<html>
  <head>
    <title>Library</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>